### PR TITLE
Clarify that our Debian installation docs also apply to the Raspberry Pi OS

### LINKED ISSUE #3: Drop Raspbian in Favor of Rasperry Pi OS
AFAIK, we're not building packages for Raspbian anymore - at least for new packages. Thus, the Raspbian.md file might be removed.

Furthermore, it should be considered removing the current packages or moving them to another location as otherwise the user's package manager says everything is up to date while the packages are getting outdated.

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #3

* CC https://github.com/Icinga/packages.icinga.com/pull/46

### CODE REVIEW

**Review by oxzi — COMMENTED** [review]
This PR introduces the same change as https://github.com/Icinga/icinga2/pull/10090 did for Icinga 2. Over there, the Raspberry Pi OS content was made identical to the Debian one.

As we have the same situation here, I would suggest removing the whole content of the file and either include the Debian content or, if this is not possible, just refer to the Debian file. Otherwise, we will end up in a situation where the content of the Debian and Raspberry Pi OS diverge.

**Comment by Al2Klimov** [comment]
Would the latter be bad, as long as it works? I mean, https://packages.icinga.com/debian/ and https://packages.icinga.com/ubuntu/ already diverged, so what?

**Comment by yhabteab** [comment]
> This PR introduces the same change as [Icinga/icinga2#10090](https://github.com/Icinga/icinga2/pull/10090) did for Icinga 2. Over there, the Raspberry Pi OS content was made identical to the Debian one.

I would also do it here exactly as it is done in Icinga 2, i.e just include the content for Debian.

**Comment by Al2Klimov** [comment]
I think the `<!-- {% include "02-Installation.md" %} -->` at EOF makes this unreasonably complicated.

**Comment by Al2Klimov** [comment]
So you'd make a common file and include it in Debian and R. Pi OS files with respective headers?

**Comment by yhabteab** [comment]
> So you'd make a common file and include it in Debian and R. Pi OS files with respective headers?

I'm trying to understand what makes you think that the *include ...* part of EOF makes it complicated. Though, why can't we just include the `Debian.md` instead of the `02-Installation.md` file?

**Comment by Al2Klimov** [comment]
> Though, why can't we just include the `Debian.md` instead of the `02-Installation.md` file?

The files here already have h1 headers, so for both OS it would be the same. Except if you do https://github.com/Icinga/package-installation-docs/pull/6#issuecomment-2355617350, but then the new helper file here would become another section. 🙈

**Comment by yhabteab** [comment]
> The files here already have h1 headers, so for both OS it would be the same.

Can't these headings be adjusted accordingly :-)?

**Comment by Al2Klimov** [comment]
I don't even know what's the include "base URL" and hence how (if at all) to include the files here. It's like you have to cat, but got no ls -R, nor pwd.

**Comment by lippserd** [comment]
Closed by #7.

**Pull request closed without merging**
